### ISSUE TITLE
Analysis failed

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#19]
# Problem

When running analysis it fails with error:
```
Analysis process has failed.

local variable 'impact_url' referenced before assignment

Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__ return self.run(*args, **kwargs) File "/usr/src/geosafe/tasks/analysis.py", line 147, in process_impact_result impact_path = download_file(impact_url) UnboundLocalError: local variable 'impact_url' referenced before assignment 
```

# Solution
Fix

**Comment by gubuntu** [comment]
@NyakudyaA is this still an issue?

**Comment by NyakudyaA** [comment]
I ran a couple of analysis on the server and haven't experienced this. I will close this and open if another issue if I experience this again
