### ISSUE TITLE
Analysis crashes and no informative output if keywords are not found in layer

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#26]
# Problem

Running an impact analysis results in the following error:
```
Task headless.tasks.inasafe_wrapper.run_analysis[8370d6c0-6ad0-4b94-9338-a235f1ba60ff] raised unexpected: KeywordNotFoundError('Keyword "structure_class_field" is not found in layer Buildings, please add it to your layer',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/src/inasafe/headless/tasks/inasafe_wrapper.py", line 84, in run_analysis
    impact_layer = run_impact_function(arguments)
  File "/home/src/inasafe/bin/inasafe.py", line 323, in run_impact_function
    impact_function.run_analysis()
  File "/home/src/inasafe/safe/impact_functions/base.py", line 950, in run_analysis
    raise e
KeywordNotFoundError: Keyword "structure_class_field" is not found in layer Buildings, please add it to your layer
[2016-12-21 14:22:21,834: INFO/MainProcess] Received task: headless.tasks.inasafe_wrapper.run_analysis[a89c9d09-01a3-47a0-93dd-59dc37e887f6]  
[2016-12-21 14:22:22,406: INFO/PoolWorker-1] Trying to download file : http://nginx/geosafe/analysis/layer-archive/62
[2016-12-21 14:22:22,452: INFO/PoolWorker-1] Trying to download file : http://nginx/geosafe/analysis/layer-archive/61
[2016-12-21 14:22:22,494: DEBUG/PoolWorker-1] CommandLineArguments
[2016-12-21 14:22:22,503: WARNING/PoolWorker-1] layer is VALID
[2016-12-21 14:22:22,509: WARNING/PoolWorker-1] layer is VALID
[2016-12-21 14:22:22,510: WARNING/PoolWorker-1] 'NoneType' object has no attribute 'startswith'
[2016-12-21 14:22:22,510: WARNING/PoolWorker-1] Attribute not found.
[2016-12-21 14:22:22,613: WARNING/PoolWorker-1] No extents
[2016-12-21 14:22:22,622: DEBUG/PoolWorker-1] createdEntire area
[2016-12-21 14:22:22,784: ERROR/PoolWorker-1] Task headless.tasks.inasafe_wrapper.run_analysis[a89c9d09-01a3-47a0-93dd-59dc37e887f6] raised unexpected: KeywordNotFoundError('Keyword "structure_class_field" is not found in layer Buildings, please add it to your layer',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/src/inasafe/headless/tasks/inasafe_wrapper.py", line 84, in run_analysis
    impact_layer = run_impact_function(arguments)
  File "/home/src/inasafe/bin/inasafe.py", line 323, in run_impact_function
    impact_function.run_analysis()
  File "/home/src/inasafe/safe/impact_functions/base.py", line 950, in run_analysis
    raise e
KeywordNotFoundError: Keyword "structure_class_field" is not found in layer Buildings, please add it to your layer
```

# Solution

fix

**Comment by gubuntu** [comment]
@NyakudyaA is this still an issue?

**Comment by NyakudyaA** [comment]
This has been fixed. There is no way that InaSAFE can detect the attributes of the layer before actually running the analysis. The keyword specified by the metadata and the attribute is only checked during analysis.
