### ISSUE TITLE
server down on impact layer

### ISSUE THREAD

**Issue by myarjunar** [kartoza/geosafe#345]
server down whenever we try to load impact layer on poduction mode (uwsgi)

logs message on rancher (geosafe-django)
```
 9/28/2018 1:37:13 AMInternal Server Error: /qgis-server/tiles/impact_analysis/14/12760/8236.png
9/28/2018 1:37:13 AMTraceback (most recent call last):
9/28/2018 1:37:13 AM  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
9/28/2018 1:37:13 AM    response = wrapped_callback(request, *callback_args, **callback_kwargs)
9/28/2018 1:37:13 AM  File "./geonode/qgis_server/views.py", line 329, in tile
9/28/2018 1:37:13 AM    os.makedirs(os.path.dirname(tile_filename))
9/28/2018 1:37:13 AM  File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
9/28/2018 1:37:13 AM    mkdir(name, mode)
9/28/2018 1:37:13 AMOSError: [Errno 17] File exists: '/usr/src/app/geonode/qgis_tiles/impact_analysis/None/14/12760'
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /qgis-server/tiles/impact_analysis/14/12760/8234.png (ip 10.42.41.151) !!!
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during GET /qgis-server/tiles/impact_analysis/14/12760/8234.png (10.42.41.151)
9/28/2018 1:37:45 AMIOError: write error
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /qgis-server/tiles/impact_analysis/14/12760/8235.png (ip 10.42.41.151) !!!
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during GET /qgis-server/tiles/impact_analysis/14/12760/8235.png (10.42.41.151)
9/28/2018 1:37:45 AMIOError: write error
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /qgis-server/tiles/impact_analysis/14/12759/8234.png (ip 10.42.41.151) !!!
9/28/2018 1:37:45 AMThu Sep 27 13:37:44 2018 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during GET /qgis-server/tiles/impact_analysis/14/12759/8234.png (10.42.41.151)
```

**Comment by myarjunar** [comment]
fixed in https://github.com/kartoza/otf-project/pull/13 cc @lucernae
